### ISSUE TITLE
Bucket perplexities increasing while global perplexity decreases

### ISSUE THREAD

**Issue by jrthom18** [suriyadeepan/easy_seq2seq#10]
I have been running this code for about 24 hours (~100,000 steps) with default parameters and it reports the global perplexity to be reasonably good now (<6). However, each of the four bucket perplexities have been rising consistently and are now very high (>10,000). What is the problem? Is this normal?

**Comment by agallardol** [comment]
Hi, I have the same issue, do you found any solution?

**Comment by dotjrt** [comment]
The issue I had was caused by this bug https://github.com/suriyadeepan/easy_seq2seq/issues/18
