### ISSUE TITLE
The links in pull_data.sh are broken

### ISSUE THREAD

**Issue by jbnunn** [suriyadeepan/easy_seq2seq#14]
I think Github may have changed something on you, the links in your bash script give 404's:

For example: 

https://media.githubusercontent.com/media/suriyadeepan/datasets/master/seq2seq/cornell_movie_corpus/processed_data/test.enc

**Comment by suriyadeepan** [comment]
Github disabled LFS on my account due to over usage. I will upload the data somewhere else and then fix the links here. ASAP

**Comment by suriyadeepan** [comment]
fixed it!
