### ISSUE TITLE
TensorFlow checkpointing V2 bug

### ISSUE THREAD

**Issue by jrthom18** [suriyadeepan/easy_seq2seq#16]
The new checkpoint saving system for TF seems to have caused an issue with this code. Now at every checkpoint 3 files are created i.e.:
```
- seq2seq.ckpt-300.data-00000-of-00001
- seq2seq.ckpt-300.index
- seq2seq.ckpt-300.meta
```

Training seems to progress normally with no errors but when I pause training and try to resume or test from the last checkpoint, a model with fresh parameters is created and my training is rendered useless.

**Temporary workaround:**
In `seq2seq_model.py` initialize `self.saver = tf.train.Saver(tf.global_variables(), write_version=1)` to revert back to the deprecated version to fix the problem. It will give a warning message about using the old version. But now I see that only two files are created at each checkpoint i.e.:
```
- seq2seq.ckpt-300
- seq2seq.ckpt-300.meta
```

Obviously this would suggest something is going on with the new write version...any ideas? I am wondering if it has something to do with the checkpoint file path in `execute.py` at the line: `model.saver.save(sess, checkpoint_path, global_step=model.global_step)`

**UPDATE:**
The problem is referenced and solved here: http://stackoverflow.com/questions/40469553/tensorflow-loading-model-with-saver-v2

**Comment by suriyadeepan** [comment]
The issue has been resolved. 
commit : 5a3603654a0adfa0c97fa6ed4ed5e4d67437785e
