### ISSUE TITLE
typo in seq2seq.ini ?

### ISSUE THREAD

**Issue by AdamSpannbauer** [suriyadeepan/easy_seq2seq#18]
question about the definitions of the train/test files in [seq2seq.ini](https://github.com/suriyadeepan/easy_seq2seq/blob/master/seq2seq.ini).

Is there a reason that both `test_enc` & `test_dec` are set to `data/test.enc`?  I'm assuming that `test_dec` should be set to `data/test.dec`.  Is this assumption correct? If my assumption is not correct could someone please explain to the logic as to why `test.enc` is used twice here?

Thanks

[lines 4-7 of seq2seq.ini]
```
train_enc = data/train.enc
train_dec = data/train.dec
test_enc = data/test.enc
test_dec = data/test.enc
```

**Comment by suriyadeepan** [comment]
thanks! fixed it..

**Comment by anksng12** [comment]
I am facing an issue with seq2seq.ini file. The error shows : ----> 6     _conf_ints = [ (key, int(value)) for key,value in parser.items('ints') ]
      7     _conf_floats = [ (key, float(value)) for key,value in parser.items('floats') ]
      8     _conf_strings = [ (key, str(value)) for key,value in parser.items('strings') ]

/home/ankit/anaconda3/lib/python3.6/configparser.py in items(self, section, raw, vars)
    844         except KeyError:
    845             if section != self.default_section:
--> 846                 raise NoSectionError(section)
    847         # Update with the entry specific variables
    848         if vars:

NoSectionError: No section: 'ints'


Any help?
Thanks
