### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by mynameisvinn** [suriyadeepan/easy_seq2seq#3]
@suriyadeepan thanks for making this public. do you plan on releasing pretrained model (that is, trained on the cornell movie dialogue corpus)?

**Comment by kauegimenes** [comment]
@mynameisvinn I think this lua module uses the cornell movie dialogue corpus by default https://github.com/macournoyer/neuralconvo

**Comment by suriyadeepan** [comment]
@mynameisvinn The reason I haven't shared it is, I'm not satisfied with the performance of the model trained on Cornell Movie corpus. But sure, I will train the model again, and share it this week. Also, I'm planning to train the same model on much larger reddit corpus which I believe will perform better.

**Comment by mynameisvinn** [comment]
@suriyadeepan sounds good! link to the reddit corpus:

https://www.reddit.com/r/datasets/comments/3bxlg7/i_have_every_publicly_available_reddit_comment/

**Comment by suriyadeepan** [comment]
Started training on Cornell Movie Dialog Corpus, with settings roughly based on neuralconvo repo. 

[neuralconvo.ini](https://github.com/suriyadeepan/easy_seq2seq/blob/master/neuralconvo.ini)

**Comment by mynameisvinn** [comment]
nice @suriyadeepan

**Comment by vgoklani** [comment]
@suriyadeepan why did you set the batchsize to 10? What's the logic behind that? are you using a GPU or CPU for training?
